# See https://redoc.ly/docs/cli/configuration/ for more information.
apiDefinitions:
  main: openapi/openapi.yaml
lint:
  extends:
    - recommended
  rules:
    no-unused-components: warning
    
referenceDocs:
  showConsole: false
  hideDownloadButton: true
  htmlTemplate: ./docs/index.html
  theme:
    colors:
      primary:
        main: "#32329f"
  generateCodeSamples:
    languages:  # Array of language config objects; indicates in which languages to generate code samples.
      - lang: curl # Can be one of the following supported languages: "curl", "Node.js", "JavaScript".
      - lang: "Node.js"
      - lang: "JavaScript"
      - lang: "C#" # Can be one of the following supported languages: "curl", "Node.js", "JavaScript".
      - lang: "GO"
    apis:
      internal@latest: 
        root: ./openapi.yaml #Dont Show End point
      external@latest:
        root: ./openapi.yaml
        lint:
          decorators:
            remove-x-internal: on      
      
      